# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chunk_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('chunk_index', models.PositiveIntegerField(help_text='Sequential position of this chunk within the document')),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('paragraph_number', models.PositiveIntegerField(blank=True, null=True)),
                ('start_char', models.PositiveIntegerField(blank=True, null=True)),
                ('end_char', models.PositiveIntegerField(blank=True, null=True)),
                ('strategy_used', models.CharField(choices=[('paragraph', 'Paragraph'), ('sentence', 'Sentence'), ('recursive', 'Recursive'), ('semantic', 'Semantic')], default='recursive', max_length=20)),
                ('chunk_size_setting', models.PositiveIntegerField(default=1024)),
                ('overlap_setting', models.PositiveIntegerField(default=150)),
                ('is_embedded', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document_upload.document')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emb_document_chunk',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vector_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=200)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('vector_dimensions', models.PositiveSmallIntegerField()),
                ('generation_time_ms', models.FloatField(blank=True, null=True)),
                ('vector_preview', models.JSONField(blank=True, help_text='First 8 dimensions of the vector, for sanity checks', null=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='embedding_service.documentchunk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emb_embedding_record',
            },
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='idx_chunk_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['is_embedded'], name='idx_chunk_embedded'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_id'], name='idx_chunk_uuid'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uq_chunk_doc_index'),
        ),
        migrations.AddIndex(
            model_name='embeddingrecord',
            index=models.Index(fields=['model_name'], name='idx_emb_model'),
        ),
        migrations.AddIndex(
            model_name='embeddingrecord',
            index=models.Index(fields=['vector_id'], name='idx_emb_vector_id'),
        ),
    ]
