# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('widget_type', models.CharField(choices=[('document_stats', 'Document Statistics'), ('recent_uploads', 'Recent Uploads'), ('indexing_queue', 'Indexing Queue'), ('recent_searches', 'Recent Searches'), ('recent_chats', 'Recent Conversations'), ('system_health', 'System Health'), ('model_status', 'Model Status'), ('storage_usage', 'Storage Usage')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration (e.g. row count to display)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widget',
                'ordering': ['user', 'position'],
                'constraints': [models.UniqueConstraint(fields=('user', 'widget_type'), name='uq_widget_user_type')],
            },
        ),
    ]
