# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Ollama model name, e.g. 'qwen3:14b-instruct'", max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('llm', 'Language Model (LLM)'), ('embedding', 'Embedding Model'), ('reasoning', 'Reasoning Model'), ('code', 'Code Model')], db_index=True, max_length=20)),
                ('ollama_url', models.URLField(default='http://127.0.0.1:11434', help_text='Ollama API base URL for this model')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='One default per model_type; enforced via admin clean()')),
                ('context_window', models.PositiveIntegerField(default=4096, help_text='Maximum context tokens supported by this model')),
                ('vector_dimensions', models.PositiveSmallIntegerField(blank=True, help_text='Output dimensions (embedding models only)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model',
                'ordering': ['model_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('rag', 'RAG Answer'), ('system', 'System Prompt'), ('summarise', 'Document Summarisation'), ('rerank', 'Re-ranking'), ('fallback', 'No-Context Fallback')], db_index=True, max_length=20)),
                ('template_text', models.TextField(help_text='Use {context}, {question}, {history} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_prompt_template',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Config', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('top_k', models.PositiveSmallIntegerField(default=5)),
                ('similarity_threshold', models.FloatField(default=0.0)),
                ('max_context_tokens', models.PositiveIntegerField(default=3000)),
                ('enable_reranking', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0.1)),
                ('top_p', models.FloatField(default=0.9)),
                ('top_k_llm', models.PositiveSmallIntegerField(default=40)),
                ('max_tokens', models.PositiveSmallIntegerField(default=1024)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('embedding_model', models.ForeignKey(blank=True, limit_choices_to={'model_type': 'embedding'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs_emb', to='ai_agent.aimodel')),
                ('llm_model', models.ForeignKey(blank=True, limit_choices_to={'model_type': 'llm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs_llm', to='ai_agent.aimodel')),
                ('rag_prompt', models.ForeignKey(blank=True, limit_choices_to={'template_type': 'rag'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs_rag', to='ai_agent.prompttemplate')),
            ],
            options={
                'db_table': 'ai_agent_config',
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_type', 'is_default'], name='idx_aimodel_type_default'),
        ),
    ]
