# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField()),
                ('raw_text', models.TextField(blank=True)),
                ('is_ocr', models.BooleanField(default=False)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'doc_document_page',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='documents/originals/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=20)),
                ('file_category', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV'), ('text', 'Plain Text'), ('html', 'HTML'), ('rtf', 'RTF'), ('pptx', 'PowerPoint'), ('image', 'Image'), ('archive', 'ZIP Archive'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ocr_required', 'OCR Required'), ('extracting', 'Extracting Text'), ('chunking', 'Chunking'), ('embedding', 'Generating Embeddings'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('doc_created_at', models.DateTimeField(blank=True, null=True)),
                ('doc_modified_at', models.DateTimeField(blank=True, null=True)),
                ('requires_ocr', models.BooleanField(default=False)),
                ('ocr_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
