# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('password_reset', 'Password Reset'), ('upload', 'Document Uploaded'), ('ocr_start', 'OCR Started'), ('ocr_complete', 'OCR Completed'), ('ocr_failed', 'OCR Failed'), ('index_start', 'Indexing Started'), ('index_complete', 'Indexing Completed'), ('index_failed', 'Indexing Failed'), ('delete_doc', 'Document Deleted'), ('search', 'Vector Search'), ('llm_call', 'LLM API Call'), ('chat_start', 'Conversation Started'), ('chat_message', 'Chat Message Sent'), ('settings_change', 'Settings Changed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('role_change', 'Role / Permission Changed'), ('error', 'Application Error')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_audit_user_date'), models.Index(fields=['action_type', 'created_at'], name='idx_audit_type_date'), models.Index(fields=['ip_address'], name='idx_audit_ip')],
            },
        ),
    ]
