# Generated by Django 5.1.15 on 2026-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('context_text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('chunks_used', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'chat_conversation_context',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_time_ms', models.FloatField(blank=True, null=True)),
                ('is_fallback_response', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['conversation', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='MessageChunkCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('similarity_score', models.FloatField()),
                ('rerank_score', models.FloatField(blank=True, null=True)),
                ('included_in_context', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_message_citation',
                'ordering': ['message', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('is_pinned', models.BooleanField(default=False)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
    ]
